### ISSUE TITLE
"Error: oauth_listener() needs an interactive environment." when running script from cron

### ISSUE THREAD

**Issue by sillasgonzaga** [dmpe/urlshorteneR#11]
I've tried to create a twitter bot using your package in which its script needs to be run automatically by using cron.

However, I've come across the `oauth_listener()` error. Is there any way to use your package in a non interactive env?

**Comment by sillasgonzaga** [comment]
Actually the solution was pretty easy. I just had to save the goo.gl token locally and `load()` it in the script.

**Comment by dmpe** [comment]
thanks for letting me know
