### ISSUE TITLE
Migrate bit.ly from v3 to v4. Test with others too

### ISSUE THREAD

**Issue by RickPack** [dmpe/urlshorteneR#13]
I am seeing Code: 500 - MISSING_ARG_ACCESS_TOKEN when I call functions including bitly_UserInfo(). Might this mean I am not properly authorized? 

`bitly_token` is not returning an error and shows:

<Token> 
<oauth_endpoint>  
  authorize: https://bitly.com/oauth/authorize  
  access:    https://api-ssl.bitly.com/oauth/access_token 
<oauth_app> bitly   
  key:    0f5320d633ef283e8dbc7165c96071033b79e3f3   
  secret: <hidden> <credentials> status_code, data, status_txt 
---

A cause of the problem could be my entries in the bit.ly OAUTH APP registration, namely:
APPLICATION LINK: http://localhost:1410/
REDIRECT URIS: http://localhost:1410/

`bitly_token$credentials$status_code` returns 401, which apparently means UNAUTHORIZED.

Forgive me, I am not very familiar with the web authentication space. A review of https://dev.bitly.com/authentication.html did not help.

**Comment by dmpe** [comment]
this weekend will reply :)

**Comment by RickPack** [comment]
Can you reopen this issue? The typo I fixed was for an unrelated example. I am still seeing the Code: 500 error. Are you? Thank you.

**Comment by dmpe** [comment]
Most probably because they have released a new API version v4 which I do not remember working with. 
https://dev.bitly.com/v4_documentation.html

This will take a (quite some) time to investigate/fix/migrate. I make no promises.

**Comment by RickPack** [comment]
Can you assign this issue to me for now? I am going to give it a try if
time allows this week. I'll let you know if I cannot complete the task. I'm
thinking the "HTTP Basic Authentication Flow" section of the bitly API
4.0.0 instructions <https://dev.bitly.com/v4_documentation.html> could help.

**Comment by RickPack** [comment]
Thanks, @dmpe. Pulled in too many directions right now.

**Comment by dmpe** [comment]
Ok, sure just, merge my recent cosmetic changes 
`git rebase` etc

**Comment by dmpe** [comment]
@senthilthyagarajan, I am working on this. Will increase the priority of this

**Comment by dmpe** [comment]
Note to myself: https://support.bitly.com/hc/en-us/articles/230647407-How-do-I-increase-my-Bitly-API-limits-

**Comment by dmpe** [comment]
@RickPack I done here. migration to v4 has been accoplished. Please test and open new issues ....thanks.
