### ISSUE TITLE
Add capacity to load saved tokens & check for token before re-auth

### ISSUE THREAD

**Issue by yogat3ch** [dmpe/urlshorteneR#20]
Hi folks!
Thanks for putting `urlshorteneR` together!
I was using it today and noticed some difficulties trying to use it non-interactively. 

I forked it and added some needed capacities for working non-interactively with the package in #19 

Hope ya'll find the modifications helpful!

**Comment by dmpe** [comment]
fixed in https://github.com/dmpe/urlshorteneR/pull/19
