### ISSUE TITLE
Allow bitly_retrieve_groups to retrieve the "general" group list

### ISSUE THREAD

**Issue by yogat3ch** [dmpe/urlshorteneR#22]
Hey folks,
It looks like `bitly_retrieve_groups` did not allow for retrieving the list of groups generally due to a `stop` check on `organization_id`, changing the default value for the argument to `NULL` and removing the `stop` fixes this in #21

Cheers!

**Comment by dmpe** [comment]
fixed in https://github.com/dmpe/urlshorteneR/pull/21
