### ISSUE TITLE
lexical error

### ISSUE THREAD

**Issue by riskcede** [dmpe/urlshorteneR#25]
Hi and thank you for your package!

Ive been using it a while and saw today that i get an error when i tried to run it.

The function I use is: isgd_LinksShorten(longUrl = long_url, showRequestURL = FALSE)

And the error I get is: Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <!--[if lt IE 7
                     (right here) ------^

I havent updated any packages lately. Ive tried various urls, i keep getting the same error.

Thanks

Regards
Jan

**Comment by riskcede** [comment]
Sorry, i see now they report that is.gd is down. This is what is causing the error.

**Comment by dmpe** [comment]
sure. thanks for the feedback :) I will close this issue now.
