### ISSUE TITLE
urlshorteneR removed from CRAN

### ISSUE THREAD

**Issue by ajlyons** [dmpe/urlshorteneR#27]
Thanks for building this awesome package!

I just wanted to flag that urlshorteneR was recently removed from CRAN: :anguished:

https://cran.r-project.org/web/packages/urlshorteneR/index.html

Looks like one of the Vignettes didn't build.

**Comment by dmpe** [comment]
Hi, this is not desired. I will contact CRAN team.

**Comment by dmpe** [comment]
package should be back online. Sorry it took me so much time and thank you for the feedback about it!!!
